### ISSUE TITLE
We need an example of config file.

### ISSUE THREAD

**Issue by judasowelu** [tomochain/tomox-market-maker#6]
We have tested the bot, and I got the error log below.

PS D:\dev\tomo_dex\tomox-market-maker> node --trace-uncaught .\cmd.js bot TOMO-BTC
TypeError: Cannot read property 'decimals' of null
    at Object.run (D:\dev\tomo_dex\tomox-market-maker\commands\bot.js:219:52)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.<anonymous> (D:\dev\tomo_dex\tomox-market-maker\cmd.js:17:9)
TypeError: Cannot read property 'decimals' of null
    at Object.run (D:\dev\tomo_dex\tomox-market-maker\commands\bot.js:219:52)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.<anonymous> (D:\dev\tomo_dex\tomox-market-maker\cmd.js:17:9)
D:\dev\tomo_dex\tomox-market-maker\node_modules\solc\soljson.js:24
(Module.asmGlobalArg,Module.asmLibraryArg,buffer);var __GLOBAL__s

////////skip////////

bort("+what+"). Build with -s ASSERTIONS=1 for more info."}Module["abort"]=abort;if(Module["preInit"]){if(typeof Module["preInit"]=="function")Module["preInit"]=[Module["preInit"]];while(Module["preInit"].length>0){Module["preInit"].pop()()}}Module["noExitRuntime"]=true;run()

abort({}). Build with -s ASSERTIONS=1 for more info.
Thrown at:
    at abort (D:\dev\tomo_dex\tomox-market-maker\node_modules\solc\soljson.js:24:12839)
    at emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

this is my config file
{
    "TOMO-BTC": {
        "pkey": "MT_WALLET_PKEY",
        "baseToken": "0x0000000000000000000000000000000000000001",
        "quoteToken": "0xBD8b2Fb871F97b2d5F0A1af3bF73619b09174B2A",
        "orderbookLength": 10,
        "speed": 60000
    },
    "wallPKey": "MT_WALLET_PKEY",
    "relayerUrl": "https://dex.testnet.tomochain.com",
    "orderbookLength": 5,
    "speed": 50000,
    "volume": 10,
    "lendingVolume": 500,
    "step": 0.01,
    "lendStep": 0.1
}

How can i run this project

**Comment by thanhson1085** [comment]
0xBD8b2Fb871F97b2d5F0A1af3bF73619b09174B2A  is not a listed token in dex testnet

**Comment by judasowelu** [comment]
i changed from 0xBD8b2Fb871F97b2d5F0A1af3bF73619b09174B2A to 0x6a4ee86a61fa8f292c8eeea26f4280186c5eaa33, but same result 

config/local.json blow
{
    "TOMO-BTC": {
        "pkey": "***",
        "baseToken": "0x0000000000000000000000000000000000000001",
        "quoteToken": "0x6a4ee86a61fa8f292c8eeea26f4280186c5eaa33",
        "orderbookLength": 10,
        "speed": 60000
    },
    "wallPKey": "***",
    "relayerUrl": "https://dex.testnet.tomochain.com",
    "orderbookLength": 5,
    "speed": 50000,
    "volume": 10,
    "lendingVolume": 500,
    "step": 0.01,
    "lendStep": 0.1
}

0x6a4ee86a61fa8f292c8eeea26f4280186c5eaa33 is testnet BTC Contract addr right?

**Comment by thanhson1085** [comment]
Try address in checksum format: 0x6a4ee86a61fA8f292c8Eeea26f4280186C5eaA33
Make sure you have enough balance for the bot.

**Comment by judasowelu** [comment]
I have 70,000 testnet TOMO which should be enough. Should I have testnet BTC as well?
I intergrated my Private Key at Testnet TomoDex and that account has 70,000 test TOMO.
When I try to buy BTC with test TOMO, it won't proceed.

check https://scan.testnet.tomochain.com/address/0xc09f4fc8b9377ff9bd9cdd83623a6626c603574b
And i tried with 0x6a4ee86a61fA8f292c8Eeea26f4280186C5eaA33 addr but still not working.

**Comment by thanhson1085** [comment]
I have no idea for now. I works OK on my side

**Comment by judasowelu** [comment]
Case solved.
Bot is running fine in Testnet Dex.
